# Site settings
title: April D. Makukhov
email: April.Makukhov@uvm.edu
url: https://amakukhov.github.io
description: "I am a 2nd year Biology PhD student in Dr. Melissa Pespeni's lab at the University of Vermont. My research addresses impacts of global change stressors on the physiology and population genomics of marine organisms."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
