# Site settings
title: April D. Makukhov
email: April.Makukhov@uvm.edu
url: https://amakukhov.github.io
description: "I am a 2nd year Biology PhD student in Dr. Melissa Pespeni's lab at the University of Vermont. My research addresses impacts of global change stressors on the physiology and population genomics of marine organisms."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google scholar
    url: https://scholar.google.com/citations?user=P773oegAAAAJ&hl=en
  - title: twitter
    url: https://twitter.com/AprilMakukhov

# Build settings
markdown: kramdown
permalink: pretty
